complete/app_complete/urls.py
from django.conf.urls import url
from app_complete import views

app_name='app_complete'

urlpatterns=[
    url('register/',views.register,name='register'),
    url('user_login/',views.user_login,name='user_login')
]

complete/complete/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from app_complete import views

import app_complete
from app_complete import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    url('app_complete/',include('app_complete.urls')),
    url('logout/',views.user_logout,name='logout')

]

complete/app_complete/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class profileinfo(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

complete/app_complete/forms.py
from django import forms
from django.contrib.auth.models import User
from app_complete.models import profileinfo

class UserForm(forms.ModelForm):
    class Meta():
        model=User
        fields=('username','password','email')

class ProfileForm(forms.ModelForm):
    class Meta():
        model=profileinfo
        fields=('portfolio','profile_pic')

complete/app_complete/views.py
from django.shortcuts import render,redirect
from app_complete.forms import UserForm,ProfileForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth import login,logout,authenticate

def index(request):
    return render(request,'app_complete/index.html')

def register(request):
    registered=False
    if request.method=='POST':
        user_form=UserForm(data=request.POST)
        profile_form=ProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.save()

            profile=profile_form.save(commit=False)
            profile.user=user
            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']
            profile.save()
            registered=True
        else:
            print('error find')
    else:
        user_form=UserForm()
        profile_form=ProfileForm()

    return render(request,'app_complete/registration.html',{'user_form':user_form,
                                                            'profile_form':profile_form,
                                                            'registered':registered})

def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return redirect(reverse('index'))
            else:
                return HttpResponse('account is not active')
        else:
            return HttpResponse("some one tried to accesur page")
    else:
        return render(request,'app_complete/login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return redirect('index')

complete/templates/app_complete/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <ul class="nav navbar nav">
            <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a> </li>
            <li><a class="navbar-link" href="{% url 'app_complete:register' %}">Register</a></li>
            <li><a class="navabar-link" href="{% url 'admin:index' %}">Admin</a></li>
            {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'logout' %}">LOGOUT</a> </li>
            {% else %}
                <li><a class="navbar-link" href="{% url 'app_complete:user_login' %}">LOGIN</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block body_block %}
    {% endblock %}
</div>

</body>
</html>

complete/templates/app_complete/index.html
{% extends 'app_complete/base.html' %}
{% block body_block %}
<h1>Welcome to the index page!</h1>
{% endblock %}

complete/templates/app_complete/login.html
{% extends 'app_complete/base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to the LOGIN page</h1>
        <form action="{% url 'app_complete:user_login'%}" method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">
            <label for="password">Password:</label>
            <input type="password" name="password" >
            <input type="submit" value="login" >


        </form>

    </div>

{% endblock %}

complete/templates/app_complete/registration.html
{% extends 'app_complete/base.html' %}
{% load static %}
{% block body_block %}
    <div class="jumbotron">
        {% if registered %}
            <h1>Thank you for registration!</h1>
        {% else %}
            <h1>Register here</h1>
            <h2>fillout the form!</h2>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" value="register">
            </form>
        {% endif %}

</div>
{% endblock %}